### ISSUE TITLE
can install laravel version >9.19

### ISSUE THREAD

**Issue by mohammadkamil** [riteshsingh1/livewire-crud#10]
**Describe the bug**
cant install on laravel project version >9.19

**Screenshots**
![image](https://user-images.githubusercontent.com/25877463/179889392-ba92e8c2-5339-4083-a2ee-1bbd40cfeb4f.png)

**Comment by rabol** [comment]
I have made a fork and corrected it
https://github.com/rabol/livewire-crud

**Comment by mohammadkamil** [comment]
thx
