### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Mokei-it** [riteshsingh1/livewire-crud#3]
Thank you for sharing your useful package.
I may help you adding localization.
Are you interested in this feature?

For example the end of lines 115 and 116 of /src/Commands/LiveCrudView.php:

from
`">Edit</a>`
`">Delete</a>`

replace with
`">{{ __('Edit') }}</a>`
`">{{ __('Delete') }}</a>`

and then add the file /resources/lang/en.json containing:
{
    "Edit": "Edit",
	"Delete": "Delete"
}

**Comment by riteshsingh1** [comment]
Sure, Please raise a PR For that.

**Comment by riteshsingh1** [comment]
Fixed in [v2.1.9](https://github.com/riteshsingh1/livewire-crud/releases/tag/v2.1.9)
