### ISSUE TITLE
Form after updating stays open

### ISSUE THREAD

**Issue by Mokei-it** [riteshsingh1/livewire-crud#5]
**Form after updating stays open**

I may be wrong, but it seems you forgot to close the form after updating the record and flashing the message.

I mean in app\Http\Livewire\model.php

`public function update(){`
`	....`
`	session()->flash('message', 'Record Updated Succesfully');`
`	$this->showForm = false;` **// I think you should add this line**
}`
Thank you!

**Comment by riteshsingh1** [comment]
Thanks for noticing, This has been updated.
